import express from 'express';

const app = express();
app.use(express.json());

// Injected sleep utility to protect OpenAI's tight 3 RPM free tier limits
const coolingDelay = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

app.post('/v1/chat/completions', async (req, res) => {
  try {
    const userPrompt = req.body.messages?.[req.body.messages.length - 1]?.content || "";
    console.log(`\n🚀 [Incoming Prompt]: ${userPrompt.substring(0, 60)}...`);

    // Strict validation to ensure global environment variables are mounted
    if (!process.env.GEMINI_API_KEY || !process.env.DEEPINFRA_API_KEY || !process.env.OPENAI_API_KEY) {
      console.error("❌ Critical Error: Missing system environment keys.");
      return res.status(500).json({ error: "Required environment variables (GEMINI_API_KEY, DEEPINFRA_API_KEY, OPENAI_API_KEY) are missing in the shell session." });
    }

    // --- TIER 1: FRONTEND GOOGLE SEARCH GROUNDING (Gemini 3.5 Flash-Lite) ---
    console.log("➡️ Running Tier 1: Scrape Web Context via Gemini 3.5 Flash-Lite...");
    const geminiUrl = `https://googleapis.com{process.env.GEMINI_API_KEY}`;
    
    const geminiPayload = {
      contents: [{ parts: [{ text: userPrompt }] }],
      tools: [{ googleSearch: {} }], // Triggers native Google web grounding
      systemInstruction: { parts: [{ text: "You are a web search agent. Output only raw, highly condensed engineering facts, documentation updates, or syntax matching the query. No conversation." }] }
    };

    const geminiRes = await fetch(geminiUrl, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(geminiPayload)
    });
    const geminiData = await geminiRes.json();
    const searchContext = geminiData.candidates?.[0]?.content?.parts?.[0]?.text || "No recent internet context found.";

    // --- TIER 2: MAIN CODESPACE LOGIC GENERATION (DeepSeek V3.2 / Coder) ---
    console.log("➡️ Running Tier 2: DeepSeek Massive Logic Generation...");
    const deepinfraUrl = "https://deepinfra.com";
    
    const deepseekPayload = {
      model: "deepseek-ai/DeepSeek-V3", 
      messages: [
        {
          role: "user",
          content: `Task: Write the core implementation matching the prompt. Leverage the appended live web search context to maintain accuracy.\n\nWEB SEARCH CONTEXT:\n${searchContext}\n\nUSER PROMPT:\n${userPrompt}`
        }
      ]
    };

    const deepseekRes = await fetch(deepinfraUrl, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${process.env.DEEPINFRA_API_KEY}`
      },
      body: JSON.stringify(deepseekPayload)
    });
    const deepseekData = await deepseekRes.json();
    const generatedLogicCode = deepseekData.choices?.[0]?.message?.content || "Code generation failed.";

    // Structural delay injection (2.5 seconds) to guarantee we do not spam OpenAI's Free Tier
    await coolingDelay(2500);

    // --- TIER 3: CRITICAL FINAL CODE REVIEW (ChatGPT o4-mini) ---
    console.log("➡️ Running Tier 3: ChatGPT o4-mini Logic Verification...");
    const openaiUrl = "https://openai.com";
    
    const o4MiniPayload = {
      model: "o4-mini",
      messages: [
        {
          role: "user",
          content: `You are an elite software auditor. Review the following code generated by DeepSeek. Check for off-by-one errors, compilation issues, or template syntax breaks. Output ONLY the optimized, perfectly corrected production code.\n\nDEEPSEEK GENERATED CODE:\n${generatedLogicCode}`
        }
      ]
    };

    const openaiRes = await fetch(openaiUrl, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${process.env.OPENAI_API_KEY}`
      },
      body: JSON.stringify(o4MiniPayload)
    });

    // Gracefully fallback to DeepSeek's raw output if OpenAI throws a free-tier 429 block
    if (openaiRes.status === 429) {
      console.log("⚠️ OpenAI Rate Limit Hit (3 RPM Cap). Returning raw DeepSeek code.");
      return res.json({
        choices: [{ message: { role: "assistant", content: `/* Note: o4-mini review bypassed due to OpenAI 3 RPM Free rate limit. Outputting raw DeepSeek-V3 generation. */\n\n${generatedLogicCode}` } }]
      });
    }

    const openaiData = await openaiRes.json();
    console.log("✅ Pipeline completed successfully!");
    res.json(openaiData);

  } catch (error) {
    console.error("❌ Pipeline Error:", error.message);
    res.status(500).json({ error: error.message });
  }
});

app.listen(4000, () => console.log('🚀 Three-Tier Gateway active on http://localhost:4000'));

