#!/bin/bash

# Generated by Google Gemini 3.5 Flash
# With my very specific requirement

export GDK_BACKEND=wayland
export LIBVA_DRIVER_NAME=i965

CHOICE=$(echo "${1:-gemini}" | tr '[:upper:]' '[:lower:]')

case "$CHOICE" in
  "gemini") TARGET_URL="https://gemini.google.com" ;;
  "youtube") TARGET_URL="https://youtube.com" ;;
  "google") TARGET_URL="https://www.google.com" ;;
  *)
    echo "ERROR: Invalid target '$1'."
    exit 1
    ;;
esac

PROFILE_DIR="$HOME/.config/mini_apps/$CHOICE"

BASE_FLAGS=(
  --ozone-platform=wayland
  --app="$TARGET_URL"
  --user-data-dir="$PROFILE_DIR"
  --no-first-run
  --no-default-browser-check
  --password-store=basic
  --js-flags="--max-old-space-size=2048 --max-semi-space-size=128"
)

if [ "$CHOICE" = "youtube" ]; then
  echo "Launching YouTube with Hardware Video Decoding..."
  rm -rf "$PROFILE_DIR/Default/Cache"
  chromium "${BASE_FLAGS[@]}" \
    --enable-features=VaapiVideoDecoder,VaapiVideoEncoder,VaapiIgnoreDriverChecks \
    --ignore-gpu-blocklist \
    --use-gl=desktop \
    --disable-features=WebRtcMediaStreamTrackRemoteVideoDecoders,AV1Decoder \
    --user-agent="Mozilla/5.0 (Apple TV; CPU OS 12_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0 Mobile/15E148 Safari/604.1"

elif [ "$CHOICE" = "google" ]; then
  echo "Enforcing System-Wide Machine Security Policies for AdGuard DoH..."
  
  SYS_POLICY_DIR="/etc/chromium/policies/managed"
  SYS_POLICY_FILE="$SYS_POLICY_DIR/adguard_doh.json"

  # If the strict system policy isn't in place, build it using sudo
  if [ ! -f "$SYS_POLICY_FILE" ]; then
    echo "[!] System policy missing. Authorizing sudo to install strict AdGuard configuration..."
    sudo mkdir -p "$SYS_POLICY_DIR"
    sudo tee "$SYS_POLICY_FILE" > /dev/null << 'EOF'
{
  "BuiltInDnsClientEnabled": true,
  "DnsOverHttpsMode": "secure",
  "DnsOverHttpsTemplates": "https://d.adguard-dns.com/dns-query/595ec64b"
}
EOF
    echo "[+] System policy applied successfully. Continue.."
  fi

  # Extension setup for layout/window lock management
  EXT_DIR="$PROFILE_DIR/extensions/tab-lock"
  mkdir -p "$EXT_DIR"

  cat << 'EOF' > "$EXT_DIR/manifest.json"
{
  "manifest_version": 3,
  "name": "Force Same Window Navigation",
  "version": "1.0",
  "permissions": ["tabs", "webNavigation"],
  "background": { "service_worker": "background.js" },
  "content_scripts": [{
    "matches": ["<all_urls>"],
    "js": ["content.js"],
    "run_at": "document_start",
    "all_frames": true
  }]
}
EOF

  cat << 'EOF' > "$EXT_DIR/content.js"
function patchLinks() {
  document.querySelectorAll('a[target]').forEach(link => link.removeAttribute('target'));
}
const observer = new MutationObserver(() => patchLinks());
observer.observe(document.documentElement, { childList: true, subtree: true });
window.addEventListener('DOMContentLoaded', patchLinks);

if (window.top === window.self) {
  const originalOpen = window.open;
  window.open = function(url, target, features) {
    if (url) { window.location.href = url; return window; }
    return originalOpen(url, target, features);
  };
}
EOF

  cat << 'EOF' > "$EXT_DIR/background.js"
chrome.tabs.onCreated.addListener((newTab) => {
  if (newTab.openerTabId) {
    chrome.tabs.onUpdated.addListener(function listener(tabId, changeInfo) {
      if (tabId === newTab.id && changeInfo.url) {
        chrome.tabs.onUpdated.removeListener(listener);
        chrome.tabs.update(newTab.openerTabId, { url: changeInfo.url });
        chrome.tabs.remove(newTab.id);
      }
    });
  }
});
EOF

  chromium "${BASE_FLAGS[@]}" \
    --ignore-gpu-blocklist \
    --use-gl=desktop \
    --load-extension="$EXT_DIR"

else
  echo "Launching Gemini in Windowed App Mode..."
  chromium "${BASE_FLAGS[@]}" \
    --ignore-gpu-blocklist \
    --use-gl=desktop \
    --disable-extensions
fi
